version: '3.1'

services:

   fence:
       image: fils/p418fence:latest
       #environment:
       #  - PORT=8000
       env_file:
         - ./local.env
       ports:
          - "8000:8000"
       networks:
          - web
      
   tangram:
       image: fils/p418tangram:latest
       ports:
          - "8080:8080"
       networks:
          - web

   headless:
       image: chromedp/headless-shell:latest
       ports:
         - "9222:9222"
       environment:
        - SERVICE_PORTS=9222
       networks:
         - web

networks:
   web:
      driver: overlay
